[cerebrium.build]
predict_data = "{\"prompt\": \"A large tree\", \"scales\": \"0,0,0,0,0,5,0\"}"
force_rebuild = false
disable_animation = false
log_level = "INFO"
disable_confirmation = false

[cerebrium.deployment]
name = "sdxl-turbo-hspace-modification"
python_version = "3.11"
include = "[main.py]"
exclude = "[./.*, ./__*]"
cuda_version = "12"

[cerebrium.hardware]
gpu = "AMPERE_A4000"
cpu = 1
memory = 12.0
gpu_count = 1

[cerebrium.scaling]
min_replicas = 0
max_replicas = 1
cooldown = 30

[cerebrium.dependencies.pip]
torch = "latest"
diffusers = "latest"
transformers = "latest"
accelerate = "latest"
pydantic = "latest"

[cerebrium.dependencies.conda]

[cerebrium.dependencies.apt]
